server:
  port: 9090

spring:
  application:
    name: microservice-analytics-java

    # Ova sekcija je ostavljena samo ako je koristite za direktnu komunikaciju sa InfluxDB klijentom,
    # ali NE koristi se za slanje metrika. Ako niste sigurni, možete je obrisati.
  influx:
   token: my-super-secret-auth-token
   bucket: nais_bucket
   org: nais_org
   url: http://influxdb:8086
   user: nais
   password: password

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

management:
  influx:
    metrics:
      export:
        enabled: true
        token: ${spring.influx.token}  # Preporučeno: Koristite referencu na gornju vrijednost
        bucket: ${spring.influx.bucket}
        org: ${spring.influx.org}
        uri: ${spring.influx.url}
        # username: nais
        # password: password